# Generated by Django 5.1.4 on 2024-12-24 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NetworksQuestionModel',
            new_name='QuestionsModel',
        ),
    ]
